# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xx}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Johnson"]
  s.date = %q{2009-08-21}
  s.description = %q{Extensions of standard ruby objects}
  s.email = %q{valde.maximus@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/extensions/array.rb",
     "lib/extensions/hash.rb",
     "lib/extensions/hash_key.rb",
     "lib/extensions/nil.rb",
     "lib/extensions/object.rb",
     "lib/extensions/parse.rb",
     "lib/extensions/pp_s.rb",
     "lib/extensions/string.rb",
     "lib/extensions/time.rb",
     "lib/xx.rb",
     "test/tc_time.rb",
     "xx.gemspec"
  ]
  s.homepage = %q{http://github.com/valdemaximus/xx}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Extensions of standard ruby objects}
  s.test_files = [
    "test/tc_time.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
